name: Deploy FastAPI Backend to Azure App Service

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: DocWise

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip backend for deployment
        run: zip -r backend.zip .
        working-directory: backend

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: backend/backend.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
