   name: Deploy FastAPI Backend to Azure App Service

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: docwise

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt
      working-directory: backend

    

    - name: Zip backend for deployment
      run: zip -r backend.zip .
      working-directory: backend

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: Production
        package: backend/backend.zip
